name: DEPLOY MANUAL

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Target deploy environment'
        type: choice
        required: true
        default: 'dev'
        options: ['dev', 'prod']

jobs:
  setup-and-deploy:
    environment: ${{inputs.env}}
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get SSM Parameters as ENV variables
        run: |
          echo "WEBAPP_S3_BUCKET=$(aws ssm get-parameter --name /webapp/s3/bucket_name | jq '.Parameter.Value' -r)" >> "$GITHUB_ENV"
          echo "WEBAPP_CDN_DISTRIBUTION_ID=$(aws ssm get-parameter --name /webapp/cdn/distribution_id | jq '.Parameter.Value' -r)" >> "$GITHUB_ENV"
          echo "VITE_COGNITO_APP_CLIENT_ID=$(aws ssm get-parameter --name /campers/cognito_client_pool_id | jq '.Parameter.Value' -r)" >> "$GITHUB_ENV"
          echo "VITE_COGNITO_AWS_POOL_ID=$(aws ssm get-parameter --name /campers/cognito_user_pool_id | jq '.Parameter.Value' -r)" >> "$GITHUB_ENV"
          echo "VITE_SENTRY_AUTH_TOKEN=$(aws ssm get-parameter --name /webapp/sentry_auth_token | jq '.Parameter.Value' -r)" >> "$GITHUB_ENV"
          echo "SENTRY_AUTH_TOKEN=$(aws ssm get-parameter --name /webapp/sentry_auth_token | jq '.Parameter.Value' -r)" >> "$GITHUB_ENV"
          echo "VITE_SENTRY_DSN=$(aws ssm get-parameter --name /webapp/sentry_dsn | jq '.Parameter.Value' -r)" >> "$GITHUB_ENV"
          echo "VITE_BMCRM_ENV=${{inputs.env}}" >> "$GITHUB_ENV"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      # - run: npm test

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          aws s3 sync dist/ s3://${{ env.WEBAPP_S3_BUCKET }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ env.WEBAPP_CDN_DISTRIBUTION_ID }} --paths "/*"
